# Exclude a variety of commonly ignored directories.
exclude = [
  ".bzr",
  ".direnv",
  ".eggs",
  ".git",
  ".git-rewrite",
  ".hg",
  ".ipynb_checkpoints",
  ".mypy_cache",
  ".nox",
  ".pants.d",
  ".pyenv",
  ".pytest_cache",
  ".pytype",
  ".ruff_cache",
  ".svn",
  ".tox",
  ".venv",
  ".vscode",
  "__pypackages__",
  "_build",
  "buck-out",
  "build",
  "dist",
  "node_modules",
  "site-packages",
  "venv",
]
line-length = 120
indent-width = 4

[format]
quote-style = "single"

[lint]
select = ["E4", "E7", "E9", "F", "B", "Q", "I", "UP"]

[lint.flake8-quotes]
inline-quotes = "single"

[lint.isort]
lines-after-imports = 2

[lint.per-file-ignores]
'src/app.py' = ["E402"]
'src/custom_types.py' = ["E402"]
'src/net.py' = ["E402"]
'src/prep.py' = ["E402"]
'src/ui.py' = ["E402"]
'src/window.py' = ["E402"]
'src/pages/generator.py' = ["E402"]
'src/pages/generator_form.py' = ["E402"]
'src/pages/generator_qr_preview_pane.py' = ["E402"]
'src/pages/old_generator.py' = ["E402"]
'src/pages/old_generator_qr_code.py' = ["E402"]
'src/pages/old_generator_starting.py' = ["E402"]
'src/pages/old_generator_wifi.py' = ["E402"]
'src/pages/scanner.py' = ["E402"]
