name: cobang # you probably want to 'snapcraft register <name>'
base: core24 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Native QR code scanner for Linux # 79 char long summary
description: |
  CoBang can scan barcode, QR code from webcam or from static image.
  To be part of Linux desktop modernization, it is set to support Wayland
  (not XWayland), and only implement native GUI (no web crap).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  cobang:
    after: ['gstreamer-gtk4']
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    source: .
    build-packages:
      - meson
      - ninja-build
      - libglib2.0-bin
      - libglib2.0-dev-bin
      - gir1.2-gtk-4.0
      - desktop-file-utils
      - blueprint-compiler
    stage-packages:
      - python3-gi
      - python3-gst-1.0
      - gir1.2-gtk-4.0
      - gir1.2-gst-plugins-base-1.0
      - gstreamer1.0-plugins-good
      - gir1.2-adw-1
      - gir1.2-nm-1.0
      - gir1.2-rsvg-2.0
      - python3-logbook
      - python3-zbar
      - python3-pil

  gstreamer-gtk4:
    plugin: dump
    build-packages:
      - build-essential
      - libgstreamer1.0-dev
      - libgtk-4-dev
      - cargo
      - cargo-c
    source: https://github.com/GStreamer/gst-plugins-rs/archive/refs/tags/gstreamer-1.24.12.tar.gz
    override-build: |
      cargo cbuild -p gst-plugin-gtk4 --prefix=/usr
    organize:
      usr/lib/**/gstreamer-1.0: usr/lib/gstreamer-1.0
    stage:
      - usr/lib/gstreamer-1.0
